name: Docker Image CI
on:
  push:
    branches: [ master ]
    tags: '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #v3.10.0
    - name: Login to DockerHub
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up variables
      run: |
        echo "repository_name=$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV
        echo "tag_name=$(echo ${{ github.ref }} | sed -e 's#refs/tags/##g' | sed -e 's#refs/heads/##g')" >> $GITHUB_ENV
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 #v6.15.0
      with:
        push: true
        tags: |
          ghcr.io/${{ env.repository_name }}:${{ env.tag_name }}
